Fix panic issue in AddDimension when creating metrics from JSON
Discovered this whilst working on the YamlMetrics collector, but it should
apply to the Adhoc collector too.

When you create a metrics.Metric struct via marshalling from JSON, it is
possible to have a nil Dimesions field. This then causes a panic when trying
to add to it:

```
=== RUN   TestAddDimensionToUnmarshalledMetric
--- FAIL: TestAddDimensionToUnmarshalledMetric (0.00s)
panic: assignment to entry in nil map [recovered]
        panic: assignment to entry in nil map

goroutine 5 [running]:
panic(0x65ad60, 0xc420013600)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc420074180)
        /usr/local/go/src/testing/testing.go:579 +0x25d
panic(0x65ad60, 0xc420013600)
        /usr/local/go/src/runtime/panic.go:458 +0x243
fullerite/metric_test.TestAddDimensionToUnmarshalledMetric(0xc420074180)
        /vagrant/src/fullerite/metric/metric_test.go:35 +0x155
testing.tRunner(0xc420074180, 0x6c59b0)
        /usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:646 +0x2ec
exit status 2
```

Fixed this by testing for the nil case and initialising with make() if it is.

Test now passes, woop!